### ISSUE TITLE
pretext task regularizer

### ISSUE THREAD

**Issue by juingzhou** [vkinakh/scatsimclr#1]
hello, I want to pretext task regularizer

**Comment by vkinakh** [comment]
Hello! For pretext task regularizer training use  **PretextTaskTrainer** 

You can do it by filling the config file, as it is shown in the [example](https://github.com/vkinakh/scatsimclr/blob/master/config_pretext.yaml)  

Then run command
`python main.py  -m=pretext -c <path to your config>`

Good luck!
