### ISSUE TITLE
random seed

### ISSUE THREAD

**Issue by StevenJ308** [vkinakh/scatsimclr#2]
Hi, I would like to ask if there is a random seed designed in your code

**Comment by vkinakh** [comment]
In the current implementation fixing random seed is not used. You can add fixed seed using the code below
```
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.backends.cudnn.deterministic = True
```

**Comment by StevenJ308** [comment]
Thank you for your answer, I still have a question in the code “logistic_regression_evaluator” line 54-79, why is there a module "train model"?

**Comment by vkinakh** [comment]
It is an evaluation procedure for the pre-trained encoder, where a small linear classification model is trained on to of these representations, thus it requires training
